"""salam model

Revision ID: c82e0fd4974f
Revises: 43b2b9a51b6d
Create Date: 2023-09-11 19:41:45.155741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c82e0fd4974f'
down_revision: Union[str, None] = '43b2b9a51b6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'myrat')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('myrat', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
